[package]
name = "quadratic-search"
version = "0.1.0"
edition = "2021"
authors = ["Wireless4024"]
keywords = ["search"]
categories = ["algorithms"]
description = """
Faster version of binary search
"""

[dependencies]

[dev-dependencies]
rand = "0.8"